from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
    INPUT_NOT_FILE = "INPUT_NOT_FILE"
    UNKNOWN_PLATFORM = "UNKNOWN_PLATFORM"
    UNKNOWN_GAME_REVISION = "UNKNOWN_GAME_REVISION"
    INVALID_REFERENCE = "INVALID_REFERENCE"
    INVALID_SCHEMA_INSTANCE = "INVALID_SCHEMA_INSTANCE"
    UNSUPPORTED_CONTROL_CODE = "UNSUPPORTED_CONTROL_CODE"
    MISSING_GLYPH = "MISSING_GLYPH"
    TEXT_OVERFLOW = "TEXT_OVERFLOW"
    RELOCATION_OVERFLOW = "RELOCATION_OVERFLOW"
    CONTAINER_REBUILD_FAILED = "CONTAINER_REBUILD_FAILED"
    COMPRESSION_ROUNDTRIP_FAILED = "COMPRESSION_ROUNDTRIP_FAILED"
    BUILD_VALIDATION_FAILED = "BUILD_VALIDATION_FAILED"


class ClassicRetroError(Exception):
    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
